# Author: Nick Benedetti (en.benedetti@pm.me)
# Aug 16, 2022
# Source https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log

name: Get information about GitHub build environment 
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
  get_shell_info:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Get set args
        # Print out the shell attribute vars
        run: echo $-
      - name: full set output
        run: set
